---
title: "Create a blog with Rstudio and Hugo"
author: "The Cobra"
date: 2017-02-04T13:19:23+01:00
categories: ["R"]
tags: ["Rstudio", "Hugo", "github"]
---

This will be a step by step tutorial on how to make your own blog with Rstudio and Hugo.

### Step one: Create github account

Sign up on https://github.com/. Github will be used as a host for your website and your profilename on github will be in the url-adress for your site, choose your github-name wisely because you will not be able to change it. 

### step two: Install blogdown and Hugo

Create a new folder, mine is called 'rweb' but you can name it whatever you want, on your computer wich will be your working direktory. Open Rstudio and click on new projekt and then choose existing directory wich will be the new folder you just created.

Next is installing blogdown and Hugo and setting your working directory. Dont forget to change to your own path in 'setwd()' and remove '#' in the beginning of lines if you copy the code below.

```{installing packages}
# install.packages("blogdown")
# install_hugo(version = "latest", use_brew = T, force)
# setwd("C:/Users/Konrad/rweb/")
```

Troubles? if not continue to next step, else run 'install.packages("evaluate")', it might clear up some errors.

### Step three: Create repositories

open https://github.com/ and log on to your profile. Click on '+' in the upper-right corner and choose New repository which you

### Step four: Install git bash